import type { PageKey } from '../App'

/**
 * 各页面标题映射，从 App.tsx 的 getPageTitle 抽离（God File 优化，审查报告 P2a）。
 */
export const PAGE_TITLES: Record<PageKey, string> = {
  dashboard: '数据概览',
  users: '用户管理',
  roles: '角色权限',
  expenses: '消费记录',
  mood: '心情日记',
  weight: '体重记录',
  notes: '笔记本',
  versions: '版本管理',
  analytics: '数据分析',
  operation_logs: '操作日志',
  system_monitor: '系统监控',
  favorites: '收藏夹',
  reminders: '提醒事项',
  habits: '习惯打卡',
  app_configs: '配置管理',
  dict_management: '字典管理',
  sensitive_words: '敏感词管理',
  sensitive_word_analytics: '敏感词数据统计',
  file_management: '文件管理',
  announcements: '公告管理',
  notifications: '通知管理',
  feedback: '问题反馈',
  anniversaries: '纪念日',
  points: '积分管理',
  checkin: '签到管理',
  error_logs: '错误日志',
  login_logs: '登录日志',
  game_configs: '游戏与维度配置',
  game_levels: '关卡配置',
  game_reward_rules: '积分奖励配置',
  game_scores: '成绩看板',
  game_analytics: '游戏数据分析',
  game_achievements: '游戏成就配置',
  game_reward_records: '游戏奖励记录',
  game_modes: '模式管理',
  game_items: '道具管理',
  pet_species: '种属管理',
  pet_rarities: '评级字典',
  pet_personalities: '性格字典',
  pet_pets: '宠物个体',
  pet_items: '道具目录',
  pet_egg_pools: '蛋池与概率',
  pet_quests: '任务池',
  pet_adventure_spots: '历险地',
  pet_evo_chains: '进化链配置',
  pet_traits: '特性池',
  pet_events: '随机事件',
  pet_achievements: '成就配置',
  pet_scenes: '场景管理',
  pet_config: '宠物全局参数',
  pet_wallets: '金币流水',
  pet_bag_adjust: '宠物运营',
  profile: '个人中心',
}
